// Directional timing judgment: delta = inputTimeMs - noteTimeMs (signed —
// negative means the press landed before the note, positive after).
// |delta| <= perfect -> "perfect"; |delta| <= good -> "good"; beyond that but
// within earlyLate on either side -> "early"/"late" (still a scored hit, just
// imprecise and direction-flagged); beyond earlyLate -> out of range, ignored
// entirely by the active keypress check (see JudgmentEngine.resolveJudgment).
// A "miss" only ever happens passively, when a note's window times out with
// no press at all (ChartManager.update()).
export const JUDGMENT_WINDOWS_MS = {
  perfect: 45,
  good: 100,
  earlyLate: 180
} as const;

// Latency calibration: audio output can reach the player's ears some ms after
// the Web Audio clock thinks playback started. effectiveSongTimeMs =
// actualAudioTimeMs - AUDIO_OFFSET_MS. Positive delays the visual/gameplay
// clock (for late-arriving audio); negative pulls it earlier.
// With PianoSynth scheduling notes directly on the AudioContext clock, only
// real device output latency remains — start from 0 and calibrate by feel.
// (The old value of 1400 was calibrated against the removed decoded-WAV path.)
export const AUDIO_OFFSET_MS = 0;

// Player-calibratable input-device latency (ms): the delay between a
// physical keypress and the browser's keydown event actually firing. Distinct
// from AUDIO_OFFSET_MS — that shifts the whole gameplay clock (visuals
// included) to match audio *output* latency, while this only nudges the
// timestamp used to judge a keypress against a note, never the rendered
// falling-note position. judgedTimeMs = songTimeMs - INPUT_LATENCY_MS:
// positive compensates for late-arriving input (judge it as if it happened
// earlier); negative assumes input arrives early.
export const INPUT_LATENCY_MS = 0;

export const NOTE_TYPES = ["tap", "slide"] as const;
export type NoteType = (typeof NOTE_TYPES)[number];

export interface ChartNote {
  id: string;
  time: number; // ms, relative to song start
  x: number; // lane index 0-7
  type: NoteType;
}

export interface ChartMeta {
  title: string;
  bpm: number;
  songLengthMs: number;
}

export interface ChartData {
  meta: ChartMeta;
  notes: ChartNote[];
}

// Score data (fetched from /scores/<id>.json, generated by
// scripts/parse-sheet.js): the FULL piano performance — every note the
// in-game piano plays. The song's chart is a thinned subset of these exact
// onsets (scripts/generate-chart.js), which is what guarantees audio/chart
// sync: both derive from this one file.
export interface ScoreNote {
  time: number; // ms, relative to song start
  durationMs: number;
  midi: number; // MIDI pitch 0-127
  velocity: number; // 0.0-1.0
  hand: "L" | "R"; // left hand -> lanes 0-3, right hand -> lanes 4-7
}

export interface ScoreData {
  meta: {
    title: string;
    bpm: number;
    durationMs: number;
  };
  notes: ScoreNote[];
}

// Song Select manifest (fetched from /songs.json): each entry maps a song's
// score (playback source) to one or more selectable difficulty charts, keyed
// by difficulty name (e.g. "Normal"). scoreUrl/chart paths are fetchable
// URLs, loaded lazily — only once a song is actually chosen in SONG_SELECT,
// never all up front.
export interface SongManifestEntry {
  id: string;
  title: string;
  artist: string;
  bpm: number;
  scoreUrl: string;
  charts: Record<string, string>;
}

export type SongManifest = SongManifestEntry[];

// Tap notes stay hittable/rendered until this long after their hit time.
export const MISSED_WINDOW_MS = JUDGMENT_WINDOWS_MS.good;

// Slide notes use a single, wider window for both the "is a held/pressed key
// close enough" check and the miss cutoff — no separate start/end phase.
export const SLIDE_WINDOW_MS = 100;

export const SCORE_VALUES = {
  perfect: 1000,
  good: 500,
  early: 150, // 30% of GOOD, per spec — still scores, but rewards precision over a rushed/late hit
  late: 150,
  miss: 0
} as const;

export const JUDGMENT_TEXT_DURATION_MS = 500;
export const JUDGMENT_POP_DURATION_MS = 100; // birth scale-pop, a portion of the full float lifespan above

// Hit-particle burst: position is a pure function of (songTimeMs - spawnTime),
// never incrementally simulated, so particles freeze exactly in place on pause.
export const PARTICLE_LIFESPAN_MS = 200;
export const PARTICLE_COUNT_MIN = 12;
export const PARTICLE_COUNT_MAX = 16;
export const PARTICLE_FRICTION = 1 / 60; // per-ms velocity decay constant

export const KEY_FLASH_DURATION_MS = 100;
export const COMBO_POP_DURATION_MS = 150;
export const SCREEN_SHAKE_MAGNITUDE_PX = 3;

// Logical design resolution. All gameplay/render math operates in this fixed
// coordinate space; the Renderer scales+letterboxes it to fit the real window,
// so hit-testing and visuals stay consistent regardless of actual screen size/aspect.
export const BASE_WIDTH = 1920;
export const BASE_HEIGHT = 1080;

export const GAME_STATES = [
  "LOADING",
  "TITLE",
  "SONG_SELECT",
  "SETTINGS",
  "DIFFICULTY_SELECT",
  "GAMEPLAY",
  "PAUSED",
  "RESULTS",
  "RECORDING"
] as const;
export type GameState = (typeof GAME_STATES)[number];

// Deterministic sort order for the DIFFICULTY_SELECT picker's rows,
// regardless of a song's charts JSON key order.
export const DIFFICULTY_ORDER = ["Easy", "Normal", "Hard"] as const;

// Cosmetic cross-fade when switching states. Timed off performance.now(), not
// songTimeMs, since TITLE has no audio clock yet and RESULTS has none running.
export const STATE_FADE_DURATION_MS = 400;

// Pre-game countdown lead-in: GAMEPLAY's song-time clock starts at
// -COUNTDOWN_MS and rises to 0 (see AudioManager.restart()'s leadInMs param),
// so notes fall in normally during the countdown instead of the first note
// appearing at the judgment line with no time to react.
export const COUNTDOWN_MS = 3000;

// SETTINGS screen's adjustable range/step for the live AUDIO_OFFSET_MS
// override persisted via SettingsStore.
export const AUDIO_OFFSET_MIN_MS = -500;
export const AUDIO_OFFSET_MAX_MS = 500;
export const AUDIO_OFFSET_STEP_MS = 5;

export const GRADE_THRESHOLDS = { S: 95, A: 90, B: 80 } as const;
export type Grade = "S" | "A" | "B" | "C";

export const RETRY_BUTTON_RECT = {
  x: BASE_WIDTH / 2 - 160,
  y: BASE_HEIGHT * 0.78,
  width: 320,
  height: 90
} as const;

// Global volume control: shared by SONG_SELECT and the PAUSED overlay, both
// as the click-to-mute hit-test rect and the drawVolumeBar() layout rect, so
// the two screens can never drift out of sync with each other.
export const VOLUME_STEP = 0.05;

// Width of the "VOL" icon segment within VOLUME_BAR_RECT \u2014 shared between
// drawVolumeBar() (rendering) and main.ts (click-to-mute vs. click/drag-to-
// set-level hit-testing), so the clickable regions can never drift out of
// sync with what's actually drawn.
export const VOLUME_ICON_WIDTH = 46;

export const VOLUME_BAR_RECT = {
  x: BASE_WIDTH - 340,
  y: 40,
  width: 300,
  height: 40
} as const;

// GAMEPLAY-only song-progress bar (elapsed/total + percent). Centered along
// the top edge; kept clear of the top-right score HUD (drawHud ends ~x=1888)
// by centering in the remaining top-center span.
export const PROGRESS_BAR_RECT = {
  x: BASE_WIDTH / 2 - 400,
  y: 40,
  width: 800,
  height: 28
} as const;

// Deemo-style vertical fall layout: fixed 8-lane grid, split across two
// keyboard rows for left/right hand separation.
export const LANE_COUNT = 8;
export const JUDGMENT_LINE_Y = 0.85; // fraction of BASE_HEIGHT

// Dynamic scroll scaling: a note's fall speed (px/ms) scales linearly with
// the loaded chart's BPM, so every song takes the same number of BEATS for a
// note to fall from the top of the screen to the judgment line, regardless of
// tempo — slow songs get a slower noteVelocity, fast songs a faster one.
// computeLookaheadMs derives how far ahead of its hit time (ms) a note must
// become "active" to already be fully on-screen at that velocity, so slower
// songs automatically look further ahead and spawn notes earlier. Purely
// visual/spawn-timing — never touches hit-timing/judgment windows above.
export const BASE_BPM = 120;
export const BASE_NOTE_SPEED = 0.5; // px per ms of lead time, at BASE_BPM

export function computeNoteVelocity(bpm: number): number {
  return BASE_NOTE_SPEED * (bpm / BASE_BPM);
}

export function computeLookaheadMs(noteVelocity: number): number {
  return (JUDGMENT_LINE_Y * BASE_HEIGHT) / noteVelocity;
}

// event.code values (layout-independent), left hand on the top row, right
// hand on home row — lanes 0-3 occupy the left half of the screen, 4-7 the right.
export const KEY_LANE_MAP: Record<string, number> = {
  KeyQ: 0,
  KeyW: 1,
  KeyE: 2,
  KeyR: 3,
  KeyJ: 4,
  KeyK: 5,
  KeyL: 6,
  Semicolon: 7
};

// Display text for each event.code — most codes are already the letter
// ("KeyQ" -> "Q"); a few punctuation codes need an explicit label.
const CODE_LABELS: Record<string, string> = { Semicolon: ";" };
function labelForCode(code: string): string {
  return CODE_LABELS[code] ?? code.replace(/^Key/, "");
}

// Derived from KEY_LANE_MAP so the on-screen key captions can never drift out
// of sync with the actual input mapping.
export const LANE_LABELS: string[] = Object.entries(KEY_LANE_MAP).reduce<string[]>((labels, [code, lane]) => {
  labels[lane] = labelForCode(code);
  return labels;
}, new Array(LANE_COUNT).fill("?"));
